{% set python_min = python_min|default("3.9") %}
{% set name = "petsird" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 214faeed5ed66143f5507895b1274b4ce3c160f0bf3bb57862b7a5d2a83d6715

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22

test:
  imports:
    - petsird
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Library and tools for working with Positron Emission Tomography Standardization Initiative Raw Data (PETSIRD)
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/ETSInitiative/PETSIRD

extra:
  recipe-maintainers:
    - gschramm
    - KrisThielemans
    - casperdcl
