schema_version: 1

context:
  version: "0.10.0"

recipe:
  name: petsird
  version: ${{ version }}

build:
  number: 1
  skip:
    - win
    - osx and not arm64

outputs:
  - package:
      name: petsird
    source:
      - url: https://pypi.org/packages/source/p/petsird/petsird-${{ version }}.tar.gz
        sha256: cc63f8d3605b44668567ecdee2c355ac78c8e1ba4f55ba31d54215a82812e282
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - setuptools >=42
        - setuptools-scm >=3.4
        - pip
      run:
        - python >=${{ python_min }}
        - numpy >=1.22
    tests:
      - python:
          imports:
            - petsird
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - "*"
  - package:
      name: libpetsird
    source:
      - if: target_platform == "linux-64"
        then:
          url: https://github.com/ETSInitiative/PETSIRD/releases/download/v${{ version }}/petsird_v${{ version }}_linux_x86_64.tar.gz
          sha256: 3edc9333cbe3b801c1581df1d31ce8f57d04b1ef82367197bdfadb4e8e88f278
      - if: target_platform == "osx-arm64"
        then:
          url: https://github.com/ETSInitiative/PETSIRD/releases/download/v${{ version }}/petsird_v${{ version }}_darwin_arm64.tar.gz
          sha256: ca84943e71184e9a8253faac269c7dee1257896b233889752ea10c785a509284
    build:
      script: cp -R include lib $PREFIX
      files:
        - include/*
        - lib/*
    tests:
      - package_contents:
          include:
            - petsird_helpers.h
            - petsird/types.h
            - petsird/protocols.h
            # self-distributed yardl (i.e. under petsird/) since there is no yardl-headers conda package (yet) to pin to instead
            - petsird/yardl/yardl.h
          files:
            - lib/cmake/PETSIRD-*/PETSIRDConfig.cmake
            - lib/cmake/PETSIRD-*/PETSIRDConfigVersion.cmake
            - lib/*petsird.* # libpetsird.a or equivalent should be present

about:
  summary: Library and tools for working with Positron Emission Tomography Standardization Initiative Raw Data (PETSIRD)
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ETSInitiative/PETSIRD

extra:
  recipe-maintainers:
    - gschramm
    - KrisThielemans
    - casperdcl
